Get http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
  "text" : "Get Bread"
} 

###
DELETE http://localhost:3001/todo/delete/6376b331ac4c25b425b55ec3

###

PUT http://localhost:3001/todo/complete/6376bc46a5410516ffa3e9d8

